name: bipolo-dev
channels:
  - conda-forge
dependencies:
- python=2.7
- anaconda
- mysql-python
- sqlalchemy=1.1
- beautifulsoup4=4.6
- selenium=3.6
- pandas=0.20
- requests=2.1
- lxml=3.8
- jupyter
- matplotlib
- cssselect=1.0
- xlrd
- flask=0.12
- jinja2=2.10
- wtforms=2.1
- flask-sqlalchemy=2.1
- flask-login=0.4.0
- seaborn=0.8
- nltk=3.2.4
- scipy=0.19.1
- openpyxl
